# Generated by Django 6.0.3 on 2026-05-26 10:06

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GareIDF",
            fields=[
                ("id", django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ("geo_point", models.CharField(db_column="Geo Point", max_length=100)),
                ("geo_shape", models.TextField(db_column="Geo Shape")),
                ("picto_ligne", models.URLField(db_column="picto ligne", max_length=500)),
                ("objectid_1", models.IntegerField(db_column="OBJECTID_1")),
                ("gares_id", models.IntegerField()),
                ("id_ref_zdc", models.IntegerField(db_column="id_ref_ZdC")),
                ("id_ref_zda", models.IntegerField(db_column="id_ref_ZdA")),
                ("nom_long", models.CharField(max_length=255)),
                ("nom_so_gar", models.CharField(blank=True, max_length=255)),
                ("nom_su_gar", models.CharField(blank=True, max_length=255)),
                ("nom_zdc", models.CharField(db_column="nom_ZdC", max_length=255)),
                ("nom_zda", models.CharField(db_column="nom_ZdA", max_length=255)),
                ("nom_iv", models.CharField(max_length=255)),
                ("idrefliga", models.CharField(max_length=50)),
                ("idrefligc", models.CharField(max_length=50)),
                ("res_com", models.CharField(max_length=100)),
                ("indice_lig", models.CharField(max_length=10)),
                ("mode", models.CharField(max_length=50)),
                ("exploitant", models.CharField(max_length=100)),
                ("tertrain", models.IntegerField()),
                ("terrer", models.IntegerField()),
                ("termetro", models.IntegerField()),
                ("tertram", models.IntegerField()),
                ("terval", models.IntegerField()),
                ("idf", models.IntegerField()),
                ("principal", models.IntegerField()),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
            ],
            options={
                "verbose_name": "Gare Île-de-France",
                "verbose_name_plural": "Gares Île-de-France",
                "db_table": "jeu_des_trains_collections",
                "managed": False,
            },
        ),
    ]
